Demo new 2 (#36)
* demo update to v3

* demo update to v3 to v1

* demo update to Failed - Cancelled

* demo update to Failed - Cancelled-2

diff --git a/.github/workflows/ami-setup.yml b/.github/workflows/ami-setup.yml
--- a/.github/workflows/ami-setup.yml
+++ b/.github/workflows/ami-setup.yml
@@ -190,17 +190,16 @@ jobs:
           run: |
             ASG_NAME="${{ steps.get_asg_and_lt.outputs.asg_name }}"
             REFRESH_STATUS=""
-            while [[ "$REFRESH_STATUS" != "Successful" && "$REFRESH_STATUS" != "Failed" ]]; do
-              REFRESH_STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME --query 'InstanceRefreshes[0].Status' --output text)
-    
-              echo "Instance Refresh Status: $REFRESH_STATUS"
-              sleep 15
+            
+            while true; do
+            REFRESH_STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME --query 'InstanceRefreshes[0].Status' --output text)
+              sleep 10
+              if [ "$REFRESH_STATUS" = "Successful" ]; then
+                echo "Instance refresh completed successfully"
+                exit 0
+              elif [ "$REFRESH_STATUS" = "Cancelled" ]; then
+                echo "Instance refresh failed"
+                exit 1
+              fi
             done
-              
-            # Check the instance refresh status and fail the workflow if it failed
-            if [[ "$REFRESH_STATUS" == "Cancelled" ]]; then
-              echo "Instance refresh failed. Workflow failed."
-              exit 1
-            else
-              echo "Instance refresh completed successfully."
-            fi
+
